### ISSUE TITLE
no puedo instalar npm 

### ISSUE THREAD

**Issue by Ratz77** [jerosoler/newpct-auto#1]
hola uso openmediavault ( debian) pero al intentar instalar npm como paso previo obtengo este error.
 apt-get install npm
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias
Leyendo la información de estado... Hecho
No se pudieron instalar algunos paquetes. Esto puede significar que
usted pidió una situación imposible o, si está usando la distribución
inestable, que algunos paquetes necesarios aún no se han creado o se
han sacado de «Incoming».
La siguiente información puede ayudar a resolver la situación:

Los siguientes paquetes tienen dependencias incumplidas:
 npm : Depende: node-gyp (>= 0.10.9) pero no va a instalarse
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos.

..
puiedes echarme una mano?

**Comment by jerosoler** [comment]
Prueba  hacer esto: 
sudo apt-get autoremove

sudo apt-get autoclean

sudo apt-get update

sudo apt-get -f install

Saludos!
