### ISSUE TITLE
Lleva 3 días que no me añade los torrents

### ISSUE THREAD

**Issue by jab3** [jerosoler/newpct-auto#2]
Buenos días! 

Desde hace 3 días no me añade Lita nuevos capítulos a descargar,  el bot por Telegram me avisa de que hay un nuevo capítulo, seguramente me dice que lo añade y al verificarlo en el transmission  no aparece .

No se si es porque ha cambiado algo en la web o simplemente es que a mi no me funciona.

Actualmente funciona correctamente? 

Gracias

**Comment by jerosoler** [comment]
@jab3 
Arreglado. Vuelve a descargar o substituye el fichero app.js

Cambios modificados
https://github.com/jerosoler/newpct-auto/commit/9cdfdb1a5d13a0a6f4834a465cd032b36fc39b0b

**Comment by jab3** [comment]
Esto es rapidez y lo demás es tontería! 

Ya comentaré que tal fue

Gracias

**Comment by jerosoler** [comment]
Okey! Perfect! 
El problema es que han puesto más publicidad y detectaba más enlaces. 

Espero feedback para cerrar el tema! 

Jero
